quarkus:
  #Configure CORS policies
  http:
    host: 0.0.0.0
    cors:
      ~: true
      origins: '*'
  #Swagger Configurations
  swagger-ui:
    enable: true

migration:
  enabled: false
import-export:
  export-enabled: false
  import-enabled: false
  file-metadata-enabled: false
