quarkus:
  resteasy-reactive:
    default-produces: application/json
  # https://quarkus.io/guides/all-config
#  thread-pool:
#    core-threads: 2
#    max-threads: 4
#    queue-size: 5
  vertx:
    max-event-loop-execute-time: 200000
    max-worker-execute-time: 200000
    warning-exception-time: 300000
  http:
    port: 8989
    cors:
      ~: true
      methods: GET, POST, PATCH, OPTIONS
      headers: accept, origin, authorization, content-type, x-requested-with, X-Forwarded-For, API-Key, SameSite, X-Host-Name
  # Health check probes
  smallrye-health:
    root-path: /health
  #Swagger Configurations
  swagger-ui:
    enable: true
    path: /q/swagger-ui
  smallrye-openapi:
    path: /q/openapi
  log:
    level: INFO
    #Log in console in json format
    console:
      json: true
  # db connection settings: https://quarkus.io/guides/liquibase
  datasource:
    db-kind: postgresql
    username: ${datasource_username:default}
    password: ${datasource_password:default}
    jdbc:
      url: ${datasource_jdbc_url:default}
      acquisition-timeout: 15000
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    schemas: public

migration:
  enabled: false
import-export:
  export-enabled: false
  import-enabled: false
  file-metadata-enabled: false
