quarkus:
  datasource:
    db-kind: h2
    username: sa
    password: sa
    jdbc:
      driver: org.h2.Driver
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  hibernate-orm:
    database:
      generation: drop-and-create
  flyway:
    enabled: false

migration:
  enabled: false
