user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    real_ip_header X-Forwarded-For;  # Use this header to get the client's IP, Specifies the header to use for determining the real client IP.
    real_ip_recursive on;            # Trust the first non-trusted proxy IP, Ensures Nginx uses the last (leftmost) IP in the X-Forwarded-For chain if multiple IPs are listed.
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format custom_combined '[[$remote_addr - $proxy_protocol_addr - $proxy_protocol_addr - $proxy_add_x_forwarded_for]] - $remote_user [$time_local] '
                               '"$request" $status $body_bytes_sent '
                               '"$http_referer" "$http_user_agent" '
                               '"$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log custom_combined;
    client_max_body_size 200M;
    sendfile        on;
    #tcp_nopush     on;
    keepalive_timeout  65;
    #gzip  on;
    include /etc/nginx/conf.d/*.conf;
}
