version: "3.8"
services:
  nginx-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - target: 443
        published: 443
        mode: host
    networks:
      - bible-project-network

networks:
  bible-project-network:
    external: true
