version: "3.8"
services:
  nginx-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - bible-project-network

networks:
  bible-project-network:
    external: true
