# STAGE 1: Compile and Build angular application
FROM node:20.8 AS build-step
# Setting up the working directory
WORKDIR /app
# Copy package json files
COPY package*.json /app/
# Install all dependencies
RUN npm install
# Copy all files
COPY . .
# Install production build
RUN npm run build:prod
# Using official nginx image as the base image
FROM nginx:1.25.3-alpine
# Copy compiled file from build stage
COPY --from=build-step /app/dist/bible-project-fe/browser /usr/share/nginx/html
# bind nginx configuration
COPY /nginx/nginx.conf /etc/nginx/nginx.conf
# bind nginx mimetypes configuration
COPY /nginx/mime.types /etc/nginx/mime.types
# override default conf for nginx
COPY /nginx/default.conf /etc/nginx/conf.d/default.conf
# Expose Port 80
EXPOSE 80
# Start the Nginx server
CMD ["nginx", "-g", "daemon off;"]
