version: '3.8'
services:
  bible-project-postgres:
    container_name: container-pg
    image: postgres:14-alpine
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bible-project-network

  bible-project-pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4:8.11.0
    depends_on:
      - bible-project-postgres
    ports:
      - "9001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    networks:
      - bible-project-network

volumes:
  postgres-data:

networks:
  bible-project-network:
    external: true
